const Routes: any = {
  Home: "Home",
  Login: "Login",
  Register: "Register",
  ForgotPassword: "ForgotPassword",
  Specialties: "Specialties",
  Profile: "Profile",
  ProfileSegment: "ProfileSegment",
  BasicInformation: "BasicInformation",
  Address: "Address",
  Calendar: "Calendar",
  Patient: "Patient",
  Summary: "Summary",
  Notifications: "Notifications",
  Payments: "Payments",
  FamilyMembers: "FamilyMembers",
  MedicalHistory: "MedicalHistory",
  UnderlyingDiseases: "UnderlyingDiseases",
  HereditaryDiseases: "HereditaryDiseases",
  Allergies: "Allergies",
  Medication: "Medication",
  Doctors: "Doctors",
  MedicalInsurance: "MedicalInsurance",
  ThankYouPage: "ThankYouPage",
  Appointments: "Appointments",
  CollaboratorDetail: "CollaboratorDetail",
  MedicaAssistant: "MedicaAssistant",
  Menu: "Menu",
  COnfiguration: "Configuration"
};

export default Routes;
